# src/test/resources/application-test.yml

# 서버 설정
server:
  port: 8080

# Spring 설정
spring:
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:3306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME} # MySQL DB 사용자명
    password: ${DATABASE_PASSWORD} # MySQL DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 실행 시 스키마 생성 후 종료 시 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# 로깅 설정 - 테스트용
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE