name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: build/libs/*.jar
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: jar-file
    
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "jar-file/*.jar"
        target: "~/app"
        strip_components: 1
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          # 기존 서버 프로세스 찾아서 종료
          PID=$(ps -ef | grep java | grep hibi-app.jar | grep -v grep | awk '{print $2}')
          if [ ! -z "$PID" ]; then
            echo "Killing process $PID"
            kill -15 $PID
            sleep 5
            # 프로세스가 여전히 살아있다면 강제 종료
            if ps -p $PID > /dev/null; then
              kill -9 $PID
            fi
          fi
      
          # 새 JAR 파일 실행 파일로 설정
          mv *.jar hibi-app.jar
      
          # 로그 파일 정리
          if [ -f nohup.out ]; then
            mv nohup.out nohup.out.$(date +%Y%m%d%H%M%S)
          fi
      
          # nohup으로 서버 실행
          nohup java -jar hibi-app.jar > nohup.out 2>&1 &
        
          echo "서버가 백그라운드에서 실행 중입니다"
          # 프로세스 실행 확인
          sleep 5
          ps -ef | grep java


